### ISSUE TITLE
Bug d'icone : si on set met en mode "placer une adresse" avec l'icone et qu'on clique sur un bouton, l'icone suit la souris

### ISSUE THREAD

**Issue by RomainGF** [Victor-Bonin/4IF-PLD-AGILE#69]
En gros si on clique sur "ouvrir un plan" alors qu'on était en train de placer une adresse (à l'ajout d'une livraison), l'icone d'ajout de livraison est toujours là

**Comment by Victor-Bonin** [comment]
De ce que j'ai vu pas en ouvrant un plan, mais en important une nouvelle DL

**Comment by PtiLuky** [comment]
A vérifier, normalement Lulu a fini ça
