### ISSUE TITLE
Bug ouverture fichier non conforme

### ISSUE THREAD

**Issue by RomainGF** [Victor-Bonin/4IF-PLD-AGILE#86]
Ouverture d'un plan , d'une DL, calcul.
Ouverture d'une DL mais fichier incorrect, bug.

**Comment by PtiLuky** [comment]
Je n'arrive plus à reproduire le bug, toujours existant ?

**Comment by PtiLuky** [comment]
Ok, j'arrive à le retrouver

**Comment by PtiLuky** [comment]
demandeLivraison réinitialisée si on catch une erreur lors de la création d'une DL.
