### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by RomainGF** [Victor-Bonin/4IF-PLD-AGILE#89]
Lorsque on veut remonter une livraison, la barre ne se met pas au bon endroit

**Comment by PtiLuky** [comment]
Il faudrait différencier les cas où on AVANCE une livraison et où on RECULE une livraison, 
si on l'avance, la barre doit être avant la case survolée, sur on la recule après la case survolée ?

Ou autre solution : mettre toujours la barre AVANT, pour mettre en dernier on survole le "+" du coup, mais du coup si on avance on se met à "index = index(case survolée)" et si on recule à "index = index(case survolée) + 1" parce qu'il y a le décalage induit par la suppression.


Cordialement, 
La direction

**Comment by PtiLuky** [comment]
Potentiellement déjà résolu, à voir au moment du merge de Drag et Master

**Comment by clarapl** [comment]
On dirait que Romain l'a pris en compte dans le controleur 👍
